name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest

    # 允许写入仓库内容（commit & push）
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # 允许使用 GITHUB_TOKEN 推送

      # 推荐：不要直接使用 @master，改用 release tag 或 SHA（示例使用 v1，如果没有请替换为 action 的有效 tag 或 commit）
      - name: Update WakaTime README
        uses: anmol098/waka-readme-stats@v1
        with:
          # 优先使用自定义 GH_ACCESS_TOKEN（如果你在 Settings->Secrets 放了个人 PAT），
          # 否则回退到自动生成的 GITHUB_TOKEN（在大多数场景足够）
          GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN || secrets.GITHUB_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_OS: "True"
          SHOW_PROJECTS: "True"
          SHOW_TOTAL_CODE_TIME: "True"
